name: Bump

on:
  push:
    branches:
      - main
    paths:
      - .gitmodules
      - vendor/**
  workflow_dispatch:

jobs:

  ci:
    uses: ./.github/workflows/ci.yml

  bump:
    runs-on: ubuntu-latest

    needs:
      - ci

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ssh-key: "${{ secrets.DEPLOY_SSH_KEY }}"

    - run: git config --local user.email "github-actions@users.noreply.github.com"
    - run: git config --local user.name "github-actions"

    - run: echo NEW_VERSION=$(git describe --tags --abbrev=0 | python -c 'import sys; a=sys.stdin.read().strip("v\n").split("."); a[1]=str(int(a[1])+1); print(".".join(a))') >> $GITHUB_ENV
    - run: sed -i 's/^version =.\+$/version = "${{ env.NEW_VERSION }}"/' Cargo.toml
    - run: git commit -am "Version ${{ env.NEW_VERSION }}"
    - run: git tag "v${{ env.NEW_VERSION }}"
    - run: git push
    - run: git push --tags
